#!/usr/bin/env python3
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[1]
CONTRACT = json.loads((ROOT / "contracts" / "daemon.json").read_text())

DEFAULT_POLICY_VERSION = CONTRACT["default_policy_version"]

GO_HEADER = "// Code generated by scripts/generate-contracts.py; DO NOT EDIT.\n\n"


def write(path: pathlib.Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)


go_constants = f'''{GO_HEADER}package model

const (
\tDefaultPolicyVersion = "{DEFAULT_POLICY_VERSION}"
)
'''

write(ROOT / "pkg/model/contract_gen.go", go_constants)
